#!/bin/bash
#World Wide Servers by ip
#wget -q  https://www.privateinternetaccess.com/pages/network/ -O - | grep -E -o '>[^.]+\.privateinternetaccess\.com<' | tr -d '[<>]' | while read host ;do host $host ;done | awk '{print $NF}' | sort -u | xargs sudo netselect -v -s 20

# U.S Servers by ip
#wget -q  https://www.privateinternetaccess.com/pages/network/ -O - | grep -E -o '>[^.]+\.privateinternetaccess\.com<' | tr -d '[<>]' | grep us- | while read host ;do host $host ;done | awk '{print $NF}' | sort -u | xargs sudo netselect -v -s 20

tput sgr0
# Dependencies "Netselect"
if command -v netselect >/dev/null 2>&1 ; then
    printf "%b\n"

else
clear
cat <<"EOF"

Netselect is required but not found. You can download it from

http://ftp.us.debian.org/debian/pool/main/n/netselect/
http://ftp.us.debian.org/debian/pool/main/n/netselect/netselect_0.3.ds1-28+b1_i386.deb		i386
http://ftp.us.debian.org/debian/pool/main/n/netselect/netselect_0.3.ds1-28+b1_arm64.deb		ARM64
http://ftp.us.debian.org/debian/pool/main/n/netselect/netselect_0.3.ds1-28+b1_armhf.deb		ARMHF
http://ftp.us.debian.org/debian/pool/main/n/netselect/netselect_0.3.ds1-28+b1_amd64.deb		AMD64

install with sudo dpkg -i netselect_0.3.ds1-28+b1_*.deb

Your Architecture (i386, x86_64, etc.) Is
EOF
dpkg --print-architecture
    exit
fi



main() {
tput rc	
printf "%b\n" " "
printf "%b" "Checking For PIA's Fastest server...Please Wait." "\n\n"
if [ "${selection}" -eq 0 ]; then
server=$(wget -q  https://www.privateinternetaccess.com/pages/network/ -O - | grep -E -o '>[^.]+\.privateinternetaccess\.com<' | tr -d '[<>]')
else
server=$(wget -q  https://www.privateinternetaccess.com/pages/network/ -O - | grep -E -o '>[^.]+\.privateinternetaccess\.com<' | tr -d '[<>]' | grep "${LOCATION}")
fi
#
# Sudo Check -----------------------------------------------------
sudo -nv 2> /dev/null
if [ "${?}" -ne 0 ] ; then
    printf "%b" "Netselect Requires Root Access To Run" "\n\n"
fi
#-----------------------------------------------------------------
#
printf "${server}" | xargs sudo netselect -s 1 > file1
printf "%b" "Fastest Server" "\n\n"
tput setaf 1
cat file1 | awk '{print $2}'
fhostname=$(cat file1 | awk '{print $2}')
printf "%b\n"
cat file1 | awk '{printf $2}' | xargs host > file2
cAddresses=$(wc -l file2 | awk '{print $1}')
printf "%b" ""${fhostname}"";tput setaf 3;printf "%b" " Has "${cAddresses}" IP Address's" "\n\n"
tput sgr0
printf "%b" "Checking For The Fastest IP Address To "${fhostname}" " "\n"
tput setaf 2
FinalIP=$(cat file2 | awk '{print $4}' | xargs sudo netselect -s 1 | awk '{print $2}')
printf "%b\n"
printf "%b" "${FinalIP}" " "
tput setaf 3
ping -c 2 "${FinalIP}" | tail -1| awk -F '/' '{print $5 "ms"}'
printf "%b\n\n"
tput sgr0
rm file1 file2

}

menu() {
	tput setaf 2
cat <<"EOF1"
 ___   ___   _   _   _    __    _____   ___
| _,\ | _ \ | | | \ / |  /  \  |_   _| | __|
| v_/ | v / | | `\ V /' | /\ |   | |   | _|
|_|   |_|_\ |_|   \_/   |_||_|   |_|   |___|
 _   __  _   _____   ___   ___   __  _   ___   _____
| | |  \| | |_   _| | __| | _ \ |  \| | | __| |_   _|
| | | | ' |   | |   | _|  | v / | | ' | | _|    | |
|_| |_|\__|   |_|   |___| |_|_\ |_|\__| |___|   |_|
  __     ___   ___  ___    __    __       ___ __  __ __
 /  \   / _/  / _/ | __| /' _/ /' _/     / _//__\|  V  |
| /\ | | \__ | \__ | _|  `._`. `._`. __ | \_| \/ | \_/ |
|_||_|  \__/  \__/ |___| |___/ |___/ \/  \__/\__/|_| |_|
EOF1
tput sgr0
cat <<"EOF2"

Select Country

0. ALL SERVERS PIA OFFERS
1. U.S.
2. UK
3. Canada
4. Australia
5. New Zealand
6. Germany
7. Hong Kong
8. Japan
9. Israel
EOF2
tput sc
read -n 1 selection
case "${selection}" in

	0)
	LOCATION=""
	printf "%b" "Checking All Servers Takes More Time....Be Patient" "\n";;
	1)
	LOCATION="us-";;
	2)
	LOCATION="uk-";;
	3)
	LOCATION="ca-";;
	4)
	LOCATION="au-";;
	5)
	LOCATION="nz.";;
	6)
	LOCATION="de-";;
	7)
	LOCATION="hk.";;
	8)
	LOCATION="japan.";;
	9)
	LOCATION="israel";;
	*)
	clear
	menu;;
	esac
}
clear
menu
main
